import { MEVBotConfig } from '../types';

export const INITIAL_MEV_BOTS: MEVBotConfig[] = [
  {
    id: 'arbitrage',
    name: 'DEX Arbitrage Bot',
    tag: 'ARB-01',
    description: 'Cross-DEX atomic spatial arbitrage capitalizing on price discrepancies between AMM pools.',
    enabled: true,
    strategySummary: 'Detects Price_A != Price_B between Uniswap V2, SushiSwap, PancakeSwap, and Aerodrome beyond round-trip gas costs.',
    detectionMechanism: 'Continuously queries pool reserves via JSON-RPC eth_call (getReserves) or pending mempool swap logs. Computes instantaneous price deltas across pools.',
    executionLogic: 'Constructs atomic multi-swap transaction. Simulates locally via eth_call to ensure net profit > gas fee. Submits via private relay (Flashbots / MEV-Boost) to prevent front-running.',
    contractInteraction: 'Interacts with UniswapV2Router / custom FlashSwap executor. Executes token swaps in a single atomic revert-guarded call.',
    riskLevel: 'Low',
    totalDetected: 42,
    totalExecuted: 19,
    successRate: 94.7,
    profitCapturedUSD: 1420.5,
    currentStatus: 'SCANNING',
    minProfitThresholdUSD: 15.0,
    maxGasGwei: 45,
    targetRouters: ['UniswapV2Router02', 'SushiSwapRouter', 'PancakeRouter'],
  },
  {
    id: 'sandwich',
    name: 'Sandwich MEV Bot',
    tag: 'SANDWICH-02',
    description: 'Exploits high-slippage user DEX swaps by sandwiching them with front-run and back-run orders.',
    enabled: true,
    strategySummary: 'Front-runs large user swap (Tx1: Buy) and back-runs immediately after (Tx2: Sell) within the same block.',
    detectionMechanism: 'Scans mempool for unconfirmed swap transactions with slippage tolerance > 1.5% and order size > $25,000 USD.',
    executionLogic: 'Calculates optimal front-run capital to push price up to victim maximum slippage limit. Simulates 3-transaction bundle (Frontrun, Victim, Backrun). Requires exact priority gas bidding.',
    contractInteraction: 'Submits 2 atomic swap calls via private Flashbots bundle to eliminate public mempool counter-sandwich risk.',
    riskLevel: 'High',
    totalDetected: 28,
    totalExecuted: 11,
    successRate: 88.2,
    profitCapturedUSD: 3180.2,
    currentStatus: 'SCANNING',
    minProfitThresholdUSD: 50.0,
    maxGasGwei: 120,
    targetRouters: ['UniswapV2Router', 'UniswapV3Quoter'],
  },
  {
    id: 'liquidation',
    name: 'DeFi Liquidation Bot',
    tag: 'LIQ-03',
    description: 'Monitors decentralized lending protocols to liquidate under-collateralized user loan positions.',
    enabled: true,
    strategySummary: 'Liquidates underwater positions when collateral_value < borrow_value * liquidation_threshold to capture 5%-10% liquidation bonus.',
    detectionMechanism: 'Subscribes to Chainlink price oracle updates and queries user account data: liquidationCall eligibility on Aave V3 and Compound V3.',
    executionLogic: 'Borrows debt asset via flash loan, invokes protocol liquidationCall(), receives discounted collateral, swaps collateral back to debt asset, repays flash loan, transfers bonus.',
    contractInteraction: 'Calls IPool(aavePool).liquidationCall() or Compound cToken.liquidateBorrow() via custom FlashLoanLiquidator contract.',
    riskLevel: 'Medium',
    totalDetected: 14,
    totalExecuted: 6,
    successRate: 100.0,
    profitCapturedUSD: 5490.8,
    currentStatus: 'SCANNING',
    minProfitThresholdUSD: 100.0,
    maxGasGwei: 80,
    targetRouters: ['AaveV3Pool', 'CompoundV3', 'MorphoBlue'],
  },
  {
    id: 'backrun',
    name: 'Back-Running Bot',
    tag: 'BACKRUN-04',
    description: 'Profits from deterministic post-event price shifts by indexing directly behind high-impact transactions.',
    enabled: true,
    strategySummary: 'Identifies massive trades, large liquidations, or newly added liquidity pairs and captures post-event balance shifts.',
    detectionMechanism: 'Listens for oracle price updates, massive whale swaps, or new pool deployments in pending block proposals.',
    executionLogic: 'Constructs back-run trade specifying same-block target transaction hash as predecessor. Uses Flashbots non-reverting bundle order.',
    contractInteraction: 'DEX routers and oracle update listener contracts.',
    riskLevel: 'Low',
    totalDetected: 35,
    totalExecuted: 16,
    successRate: 91.4,
    profitCapturedUSD: 2150.0,
    currentStatus: 'SCANNING',
    minProfitThresholdUSD: 25.0,
    maxGasGwei: 60,
    targetRouters: ['UniswapV2Router', 'CurveRouter', 'BalancerVault'],
  },
  {
    id: 'frontrun',
    name: 'Front-Running Bot',
    tag: 'FRONTRUN-05',
    description: 'Outbids competing unconfirmed transactions to be included earlier in the block.',
    enabled: false,
    strategySummary: 'Beats victim or competing bot by dynamically submitting a higher priority gas tip (EIP-1559 maxPriorityFeePerGas).',
    detectionMechanism: 'Scans mempool for mispriced limit orders, unhedged oracle lags, or profitable public trades.',
    executionLogic: 'Calculates net yield after paying aggressive priority fee. Increments gas bid by 12.5% step rule.',
    contractInteraction: 'Target DEX router contracts, aggregators (1inch, Paraswap).',
    riskLevel: 'High',
    totalDetected: 18,
    totalExecuted: 5,
    successRate: 75.0,
    profitCapturedUSD: 890.0,
    currentStatus: 'IDLE',
    minProfitThresholdUSD: 40.0,
    maxGasGwei: 150,
    targetRouters: ['UniswapV2Router', '1inchAggregationRouter'],
  },
  {
    id: 'timebandit',
    name: 'Time-Bandit Reorg Bot',
    tag: 'BANDIT-06',
    description: 'Analyzes validator block reorganization incentives and consensus MEV reorg thresholds.',
    enabled: false,
    strategySummary: 'Theoretical validator-level MEV extraction where validators attempt 1-2 block reorganizations for catastrophic MEV blocks.',
    detectionMechanism: 'Calculates block payoff metric: checks if MEV extracted in recent blocks > expected validator staking reward over reorg depth.',
    executionLogic: 'Produces alternative fork proposals at consensus layer (engine API / consensus client). High slash & social consensus risk.',
    contractInteraction: 'No smart contract interaction — consensus layer validator beacon node proposal.',
    riskLevel: 'Extreme',
    totalDetected: 2,
    totalExecuted: 0,
    successRate: 0.0,
    profitCapturedUSD: 0.0,
    currentStatus: 'IDLE',
    minProfitThresholdUSD: 50000.0,
    maxGasGwei: 500,
    targetRouters: ['ConsensusEngineAPI', 'BeaconNodeValidator'],
  },
  {
    id: 'oracle',
    name: 'Oracle Manipulation & Guard Bot',
    tag: 'ORACLE-07',
    description: 'Detects fragile low-liquidity spot price oracles and models economic attack and defense vectors.',
    enabled: true,
    strategySummary: 'Identifies lending markets or synthetics protocols reading low-depth spot reserves or shallow TWAPs instead of Chainlink feeds.',
    detectionMechanism: 'Scans DeFi protocol oracle contracts. Checks pool liquidity depth ($k = x * y$) against capital required to distort price by 15%.',
    executionLogic: 'Simulates flash loan capital infusion to distort spot price, trigger protocol borrow, and unwind with net surplus.',
    contractInteraction: 'Vulnerable DEX pools, Lending pool oracle listeners, TWAP price accumulators.',
    riskLevel: 'Extreme',
    totalDetected: 9,
    totalExecuted: 2,
    successRate: 100.0,
    profitCapturedUSD: 6200.0,
    currentStatus: 'SCANNING',
    minProfitThresholdUSD: 250.0,
    maxGasGwei: 100,
    targetRouters: ['UniswapV2Pair', 'TWAPOracle', 'SyntheticMinter'],
  },
  {
    id: 'nft',
    name: 'NFT MEV & Sniping Bot',
    tag: 'NFT-08',
    description: 'Snipes mispriced NFT listings, rare metadata traits, and front-runs Dutch auctions.',
    enabled: true,
    strategySummary: 'Monitors NFT marketplace mempools (Seaport, LooksRare) for listings priced severely below current floor price.',
    detectionMechanism: 'Subscribes to marketplace mempool events and off-chain order books. Compares ask price against collection trait floor index.',
    executionLogic: 'Builds atomic fulfillOrder call with maximum gas tip to confirm purchase in the earliest block.',
    contractInteraction: 'Seaport 1.6, Blur Execution Delegate, LooksRare Exchange.',
    riskLevel: 'Medium',
    totalDetected: 15,
    totalExecuted: 4,
    successRate: 80.0,
    profitCapturedUSD: 1840.0,
    currentStatus: 'SCANNING',
    minProfitThresholdUSD: 80.0,
    maxGasGwei: 90,
    targetRouters: ['SeaportV1.6', 'BlurDelegate'],
  },
  {
    id: 'gasauction',
    name: 'Priority Gas Auction (PGA) Bot',
    tag: 'PGA-09',
    description: 'Automated bidding engine that competes in high-stakes gas wars for single-winner MEV opportunities.',
    enabled: true,
    strategySummary: 'Spams iterative replacement transactions with escalating priority gas bids up to the mathematical break-even cutoff.',
    detectionMechanism: 'Detects competitor transactions targeting identical arbitrage or liquidation opportunities in mempool.',
    executionLogic: 'Computes max_profitable_gas = (Expected_Profit - Minimum_Margin) / Gas_Limit. Automatically bumps nonce with higher gas.',
    contractInteraction: 'DEX routers, Aave liquidation contracts, UniswapV3Router.',
    riskLevel: 'High',
    totalDetected: 24,
    totalExecuted: 8,
    successRate: 66.7,
    profitCapturedUSD: 1980.4,
    currentStatus: 'SCANNING',
    minProfitThresholdUSD: 30.0,
    maxGasGwei: 250,
    targetRouters: ['UniswapV2Router', 'AavePool'],
  },
  {
    id: 'flashbots',
    name: 'Flashbots Private Bundle Bot',
    tag: 'FB-10',
    description: 'Zero-revert private transaction bundle submission directly to block builders via MEV-Boost.',
    enabled: true,
    strategySummary: 'Executes complex multi-transaction MEV sequences through private builder relays (Flashbots, BeaverBuild, Titan).',
    detectionMechanism: 'Integrates with all opportunity detection pipelines. Selects bundle candidates needing atomic non-reverting guarantees.',
    executionLogic: 'Packages Tx array, signs bundle with searcher authentication key, sets target block number. Simulates EVM state transition locally.',
    contractInteraction: 'Calls custom atomic MEVExecutor smart contract, routes validator coinbase tip via block.coinbase.transfer().',
    riskLevel: 'Low',
    totalDetected: 64,
    totalExecuted: 32,
    successRate: 96.9,
    profitCapturedUSD: 8740.0,
    currentStatus: 'SCANNING',
    minProfitThresholdUSD: 20.0,
    maxGasGwei: 300,
    targetRouters: ['MEVExecutor.sol', 'FlashbotsRelay', 'MEV-Boost'],
  },
];

export const DEFAULT_BOTS = INITIAL_MEV_BOTS;
